language: R
sudo: false
cache: packages
apt_packages:
  - libxml2-dev
script:
- R -e "rmarkdown::render_site('.')"
- touch _site/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
